"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { FileCheck2, FileUp, LogOut, Plus, Sparkles, Target, UploadCloud } from "lucide-react";
import { Brand } from "../../components/brand";
import { Analysis, api } from "../../lib/api";

export default function Dashboard() {
  const router = useRouter();
  const fileRef = useRef<HTMLInputElement>(null);
  const [items, setItems] = useState<Analysis[]>([]);
  const [file, setFile] = useState<File | null>(null);
  const [role, setRole] = useState("Software Engineer");
  const [busy, setBusy] = useState(false);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => { api<{ analyses: Analysis[] }>("/analyses").then(r => setItems(r.analyses)).catch(() => router.push("/login")).finally(() => setLoading(false)); }, [router]);
  async function upload(e: React.FormEvent) { e.preventDefault(); if (!file) return setError("Choose a PDF to continue."); setBusy(true); setError(""); try { const data = new FormData(); data.append("resume", file); data.append("targetRole", role); const r = await api<{ analysis: Analysis }>("/analyses", { method: "POST", body: data }); router.push(`/analysis/${r.analysis._id}`); } catch (e) { setError(e instanceof Error ? e.message : "Upload failed"); } finally { setBusy(false); } }
  function signOut() { localStorage.removeItem("resume_token"); router.push("/"); }
  return <main className="min-h-screen bg-[radial-gradient(circle_at_100%_0%,rgba(94,234,212,.18),transparent_28%),#f6faf9]"><header className="border-b border-slate-200/70 bg-white/80 backdrop-blur"><div className="mx-auto flex max-w-6xl items-center justify-between px-6 py-4"><Brand /><button className="btn-secondary text-sm" onClick={signOut}><LogOut size={16} /> Sign out</button></div></header><div className="mx-auto max-w-6xl px-6 py-10">
    <div className="reveal flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-bold tracking-[.16em] text-teal-700">YOUR WORKSPACE</p><h1 className="mt-2 text-3xl font-bold tracking-tight">Make every application count.</h1><p className="mt-2 text-slate-600">Upload, learn, refine, and repeat with confidence.</p></div><div className="rounded-xl border border-slate-200/80 bg-white px-4 py-3 text-sm shadow-sm"><span className="text-xl font-bold text-ink">{items.length}</span><span className="ml-2 text-slate-500">analyses completed</span></div></div>
    <section className="reveal reveal-delay-1 card mt-8 overflow-hidden"><div className="grid md:grid-cols-[.82fr_1.18fr]"><div className="shine relative bg-ink p-7 text-white md:p-9"><span className="grid h-10 w-10 place-items-center rounded-xl bg-white/10 text-mint"><Sparkles size={20}/></span><p className="mt-9 text-xs font-bold tracking-[.16em] text-mint">NEW ANALYSIS</p><h2 className="mt-3 text-3xl font-bold leading-tight">Ready for a sharper resume?</h2><p className="mt-4 max-w-sm leading-7 text-slate-300">We will identify the highest-impact changes for your next application.</p><div className="mt-8 flex items-center gap-2 text-sm text-slate-300"><span className="h-2 w-2 rounded-full bg-mint" /> ATS score, keyword gaps, and tailored feedback</div></div>
      <form onSubmit={upload} className="p-7 md:p-9"><label className="label">Target job role<input className="input mt-1.5" value={role} onChange={e => setRole(e.target.value)} placeholder="e.g. Product Manager" /></label><input ref={fileRef} className="hidden" type="file" accept="application/pdf" onChange={e => { setFile(e.target.files?.[0] || null); setError(""); }} /><button type="button" onClick={() => fileRef.current?.click()} className={`mt-5 flex w-full items-center gap-4 rounded-xl border-2 border-dashed px-5 py-5 text-left transition duration-200 ${file ? "border-teal-400 bg-teal-50/70" : "border-slate-200 hover:border-teal-400 hover:bg-teal-50/50"}`}><span className={`grid h-11 w-11 place-items-center rounded-xl ${file ? "bg-teal-600 text-white" : "bg-slate-100 text-teal-700"}`}>{file ? <FileCheck2 size={21}/> : <UploadCloud size={21}/>}</span><span className="min-w-0"><b className="block truncate">{file ? file.name : "Choose your resume PDF"}</b><small className="mt-1 block text-slate-500">PDF only · max 5MB · text-based file</small></span></button>{error && <p className="mt-3 text-sm font-medium text-red-600">{error}</p>}<button disabled={busy} className="btn-primary mt-5 w-full">{busy ? <><span className="h-4 w-4 animate-spin rounded-full border-2 border-white/40 border-t-white"/> Analyzing your resume...</> : <>Analyze resume <Target size={17}/></>}</button></form></div></section>
    <section className="reveal reveal-delay-2 mt-11"><div className="flex items-center justify-between"><div><h2 className="text-xl font-bold">Analysis history</h2><p className="mt-1 text-sm text-slate-500">Revisit feedback as you refine your resume.</p></div>{items.length > 0 && <button onClick={() => fileRef.current?.click()} className="btn-secondary text-sm"><Plus size={16}/> New analysis</button>}</div>{loading ? <div className="mt-5 grid gap-3">{[1, 2, 3].map(i => <div className="card h-[82px] animate-pulse bg-slate-100" key={i}/>)}</div> : items.length === 0 ? <div className="card mt-5 border-dashed p-12 text-center"><span className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-teal-50 text-teal-600"><FileUp size={27}/></span><h3 className="mt-4 font-bold">Your first insight is waiting</h3><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-slate-600">Upload a PDF above to get a focused, actionable improvement plan.</p></div> : <div className="mt-5 grid gap-3">{items.map((a, index) => <Link href={`/analysis/${a._id}`} key={a._id} className="card stagger-item flex flex-wrap items-center gap-5 p-5 transition duration-200 hover:-translate-y-0.5 hover:border-teal-300 hover:shadow-lg" style={{ animationDelay: `${index * .07}s` }}><div className="grid h-12 w-12 place-items-center rounded-xl bg-gradient-to-br from-teal-100 to-cyan-50 text-lg font-bold text-teal-800">{a.atsScore}</div><div className="min-w-[180px] flex-1"><b>{a.fileName}</b><p className="mt-1 text-sm text-slate-500">{a.targetRole} · {new Date(a.createdAt).toLocaleDateString()}</p></div><span className="rounded-full bg-slate-100 px-3 py-1.5 text-sm font-bold text-slate-700">{a.roleMatch}% role match</span></Link>)}</div>}</section>
  </div></main>;
}
